# Generated by Django 3.1.5 on 2021-02-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_image', models.ImageField(upload_to='event_images/')),
                ('the_text', models.CharField(max_length=300)),
            ],
        ),
    ]
